version: '3'
services:

  server:
    build: .
    container_name: lappupeli-server
    environment:
      - DATABASE_URL=postgresql://postgres:devdbpassword@db:5432/lappupeli
      - SECRET_KEY=devsecretkey
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:15.0-alpine"
    container_name: lappupeli-db
    volumes:
      - lappupeli-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devdbpassword
      - POSTGRES_DB=lappupeli
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1s
      timeout: 5s
      retries: 20

volumes:
  lappupeli-data:
