[tool.poetry]
name = "lappupeli"
version = "0.1.2"
description = ""
authors = ["Juho Röyskö <roysko.juho@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.1.2"
Flask-SQLAlchemy = "^2.5.1"
python-dotenv = "^0.20.0"
gunicorn = "^20.1.0"
psycopg2-binary = "^2.9.5"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
invoke = "^1.7.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
